#!/bin/sh

source ~/.config/awesome/mpd_cfg
source ~/.config/awesome/mpd_stat
source ~/.config/awesome/mpd_send

mpc -h ${h} -p ${p} ${1}

if [ ${1} != "next" ] && [ ${1} != "prev" ]
then
    mpd_status
    mpd_send
fi
