#!/bin/sh

mail() {
    count=$( curl -n --silent https://mail.google.com/mail/feed/atom/unread | \
	awk '/<fullcount>/,/<\/fullcount>/{gsub(/.*<fullcount>/,"");
             gsub(/<\/fullcount>.*/, ""); print}' )
    echo "mail.text = \"${count}\"" | awesome-client
}

rss() {
    count=$( curl --silent \
	"http://rss.mariom.pl/public.php?op=getUnread&login=mariom" )
    echo "rss.text = \"${count}\"" | awesome-client
}

updates() {
    updates=$(eix -u --only-names | wc -l)
    echo "pkg.text = \"${updates}\"" | awesome-client
}


while [ 1 ]
do
    mail
    rss
    updates

    sleep 1m
done
